<!DOCTYPE html><html><head><style>
body {font-family: '-apple-system'; font-size: 17.0px;}
h1   {font-family: '-apple-system'; f.github/workflows/main.ymlont-size: 28.0px;}
h2   {font-family: '-apple-system'; font-size: 22.0px;}
</style></head><body><ul><li>ğŸ‘‹ğŸ¾ Hi, Iâ€™m @Full3rgr33n</li><li>ğŸ‘€ Iâ€™m interested in ...</li><li>ğŸŒ± Iâ€™m currently learning ...</li><li>ğŸ’ï¸ Iâ€™m looking to collaborate on ...</li><li>ğŸ“« How to reach me ...</li></ul></body></html>
